# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Until there is support for Nuget central package management dependabot needs to be disabled 
# https://github.com/dependabot/dependabot-core/issues/4999

# version: 2
# updates:
#   - package-ecosystem: "nuget" # See documentation for possible values
#     directory: "/libraries/" # Location of package manifests
#     schedule:
#       interval: "weekly"
#     target-branch: "develop"
#     commit-message:
#       prefix: chore
#       include: scope
#   - package-ecosystem: "nuget" # See documentation for possible values
#     directory: "/examples/Idempotency/" # Location of package manifests
#     schedule:
#       interval: "weekly"
#     target-branch: "develop"
#     commit-message:
#       prefix: chore
#       include: scope
#   - package-ecosystem: "nuget" # See documentation for possible values
#     directory: "/examples/Logging/" # Location of package manifests
#     schedule:
#       interval: "weekly"
#     target-branch: "develop"
#     commit-message:
#       prefix: chore
#       include: scope
#   - package-ecosystem: "nuget" # See documentation for possible values
#     directory: "/examples/Metrics/" # Location of package manifests
#     schedule:
#       interval: "weekly"
#     target-branch: "develop"
#     commit-message:
#       prefix: chore
#       include: scope
#   - package-ecosystem: "nuget" # See documentation for possible values
#     directory: "/examples/Parameters/" # Location of package manifests
#     schedule:
#       interval: "weekly"
#     target-branch: "develop"
#     commit-message:
#       prefix: chore
#       include: scope
#   - package-ecosystem: "nuget" # See documentation for possible values
#     directory: "/examples/ServerlessApi/" # Location of package manifests
#     schedule:
#       interval: "weekly"
#     target-branch: "develop"
#     commit-message:
#       prefix: chore
#       include: scope
#   - package-ecosystem: "nuget" # See documentation for possible values
#     directory: "/examples/Tracing/" # Location of package manifests
#     schedule:
#       interval: "weekly"
#     target-branch: "develop"
#     commit-message:
#       prefix: chore
#       include: scope
