name: Label PR based on title

on:
  workflow_run:
    workflows: ["Record PR details"]
    types:
      - completed

jobs:
  get_pr_details:
    permissions:
      id-token: write
    # Guardrails to only ever run if PR recording workflow was indeed
    # run in a PR event and ran successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable_export_pr_details.yml
    with:
      record_pr_workflow_id: ${{ github.event.workflow_run.id }}
      workflow_origin: ${{ github.event.repository.full_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  label_pr:
    permissions:
      id-token: write
    needs: get_pr_details
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: "Label PR based on title"
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          PR_NUMBER: ${{ needs.get_pr_details.outputs.prNumber }}
          PR_TITLE: ${{ needs.get_pr_details.outputs.prTitle }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # This safely runs in our base repo, not on fork
          # thus allowing us to provide a write access token to label based on PR title
          # and label PR based on semantic title accordingly
          script: |
            const script = require('.github/scripts/label_pr_based_on_title.js')
            await script({github, context, core})
